global:
  scrape_interval: 15s
  evalution_interval: 15s
  external_labels:
    monitoring: "tf-serving-monitor"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s 
    metrics_path: /monitoring/prometheus/metrics 
    static_configs:
      - targets: ['<External IP>:8501']